In [6]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

In [7]:
params_df = pd.read_excel("C:\\Users\\Nefeli\\Desktop\\opti2_stat_scripts\\pso_results\\pso_full.xlsx")

In [12]:
minimized_df = params_df.copy(deep=True)
to_drop = ['expID_list', 'costVal_list', 'lastHit_list','feasibility_list',
          'costVal_mean', 'lastHit_mean','feasibility_mean','feasibility_median',
          'costVal_std', 'lastHit_std','feasibility_std',
          'costVal_min', 'lastHit_min','feasibility_min',
          'costVal_max', 'lastHit_max','feasibility_max']
minimized_df.drop(to_drop, axis=1, inplace=True)
minimized_df

nb_r    N  costVal_median  lastHit_median
0     0   50      432.035678           90262
1     0  100      424.942921          104769
2     0  200      423.887200           84060
3     5   50      428.101784          103317
4     5  100      422.542661          116953
5     5  200      413.673383          159847

Helper Functions

In [13]:
#isolates data that corresponds to a file 
#and gets the median result for the column defined as input, for each parametrization
def getMediansOf(minimized_df,columnName):
    outputList=[]
    for i in range(1):
        subDf = minimized_df
        resPerFile=[]
        for j in range(6):
            resPerFile.append(subDf.iat[j, subDf.columns.get_loc(columnName)])
        outputList.append(resPerFile)
    return outputList

### Wilcoxon on Cost Value Medians 

In [16]:
costValList = getMediansOf(minimized_df,'costVal_median')

outdfC = pd.DataFrame(costValList,columns=['(0,50)','(0,100)','(0,200)','(5,50)','(5,100)','(5,200)'],index=['0'])
outdfC

(0,50)     (0,100)   (0,200)      (5,50)     (5,100)     (5,200)
0  432.035678  424.942921  423.8872  428.101784  422.542661  413.673383

In [17]:
latex_table = outdfC.to_latex(
    index=False,        # Exclude row indices
    column_format='|c|c|c|c|c|c|c|',  # Specify column formatting
    escape=False        # Disable LaTeX escaping of special characters
)

# Print the LaTeX table or save it to a .tex file
print(latex_table)

\begin{tabular}{|c|c|c|c|c|}
\toprule
(0,50) & (0,100) & (0,200) & (5,50) & (5,100) & (5,200) \\
\midrule
432.035678 & 424.942921 & 423.887200 & 428.101784 & 422.542661 & 413.673383 \\
\bottomrule
\end{tabular}



In [19]:
pVal_matrix_costVals = np.zeros((6,6))
H0_rej_matrix_costVals = np.zeros((6,6))
p = ['(0,50)','(0,100)','(0,200)','(5,50)','(5,100)','(5,200)']
for i in range(6):
    current = outdfC[p[i]].values
    for j in range(6):
        if i==j:
            #necessary step because 
            pVal_matrix_costVals[i][j]= 10 # a pvalue cannot take a value of 10 
        else:
            statistic,pvalue = stats.wilcoxon(current,outdfC[p[j]].values, alternative='two-sided')
            pVal_matrix_costVals[i][j]=pvalue

print(p)
for i in range(6):
    print(str(p[i])+str(pVal_matrix_costVals[i][:]))
    
for i in range(6):
    for j in range(6):
        if pVal_matrix_costVals[i][j]<0.05:
            H0_rej_matrix_costVals[i][j]= 1
print(H0_rej_matrix_costVals)  

['(0,50)', '(0,100)', '(0,200)', '(5,50)', '(5,100)', '(5,200)']
(0,50)[10.  1.  1.  1.  1.  1.]
(0,100)[ 1. 10.  1.  1.  1.  1.]
(0,200)[ 1.  1. 10.  1.  1.  1.]
(5,50)[ 1.  1.  1. 10.  1.  1.]
(5,100)[ 1.  1.  1.  1. 10.  1.]
(5,200)[ 1.  1.  1.  1.  1. 10.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### Wilcoxon on Last Hit

In [22]:
lastHitList = getMediansOf(minimized_df,'lastHit_median')

outdfL = pd.DataFrame(lastHitList,columns=['(0,50)','(0,100)','(0,200)','(5,50)','(5,100)','(5,200)'],index=['0'])
outdfL

(0,50)  (0,100)  (0,200)  (5,50)  (5,100)  (5,200)
0   90262   104769    84060  103317   116953   159847

In [23]:
latex_table = outdfL.to_latex(
    index=False,        # Exclude row indices
    column_format='|c|c|c|c|c|c|c|',  # Specify column formatting
    escape=False        # Disable LaTeX escaping of special characters
)

# Print the LaTeX table or save it to a .tex file
print(latex_table)

\begin{tabular}{|c|c|c|c|c|c|c|}
\toprule
(0,50) & (0,100) & (0,200) & (5,50) & (5,100) & (5,200) \\
\midrule
90262 & 104769 & 84060 & 103317 & 116953 & 159847 \\
\bottomrule
\end{tabular}



In [25]:
pVal_matrix_lastHit = np.zeros((6,6))
H0_rej_matrix_lastHit = np.zeros((6,6))
p = ['(0,50)','(0,100)','(0,200)','(5,50)','(5,100)','(5,200)']
for i in range(6):
    current = outdfL[p[i]].values
    for j in range(6):
        if i==j:
            #necessary step because 
            pVal_matrix_lastHit[i][j]= 10 # a pvalue cannot take a value of 10 
        else:
            statistic,pvalue = stats.wilcoxon(current,outdfL[p[j]].values, alternative='two-sided')
            pVal_matrix_lastHit[i][j]=pvalue

print(p)
for i in range(6):
    print(str(p[i])+str(pVal_matrix_lastHit[i][:]))
    
for i in range(6):
    for j in range(6):
        if pVal_matrix_lastHit[i][j]<0.05:
            H0_rej_matrix_lastHit[i][j]= 1
print(H0_rej_matrix_lastHit)

['(0,50)', '(0,100)', '(0,200)', '(5,50)', '(5,100)', '(5,200)']
(0,50)[10.  1.  1.  1.  1.  1.]
(0,100)[ 1. 10.  1.  1.  1.  1.]
(0,200)[ 1.  1. 10.  1.  1.  1.]
(5,50)[ 1.  1.  1. 10.  1.  1.]
(5,100)[ 1.  1.  1.  1. 10.  1.]
(5,200)[ 1.  1.  1.  1.  1. 10.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
